### ISSUE TITLE
Executables in `dummy_sensors`

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#593]
## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Checks
- [ ] **Check `dummy_joint_states`**

     

  <details><summary>details</summary>
  
    **Try**
  
    1.
       ```bash
       # User input in terminal 1
       ros2 run dummy_sensors dummy_joint_states
       ```
  
    
  </details>
- [ ] **Check `dummy_laser`**

     

  <details><summary>details</summary>
  
    **Try**
  
    1.
       ```bash
       # User input in terminal 1
       ros2 run dummy_sensors dummy_laser
       ```
  
    
  </details>

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by wep21** [comment]
- dummy joint states
```
❯ ros2 topic echo /joint_states --once
header:
  stamp:
    sec: 1683363361
    nanosec: 367613546
  frame_id: ''
name:
- single_rrbot_joint1
- single_rrbot_joint2
position:
- 0.9154525466207135
- 0.9154525466207135
velocity: []
effort: []
---
```
- dummy_laser
```
❯ ros2 run dummy_sensors dummy_laser
[INFO] [1683363407.173798802] [dummy_laser]: angle inc:	0.004363
[INFO] [1683363407.173870732] [dummy_laser]: scan size:	1081
[INFO] [1683363407.173876432] [dummy_laser]: scan time increment: 	0.000028
```
